# Generated by Django 4.1.2 on 2022-11-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fechaAlta', models.DateField(verbose_name='Fecha Alta')),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('mobile', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150, null=True)),
                ('precio', models.FloatField(max_length=150, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webAdrianBMbiblioteca.autor')),
            ],
        ),
    ]
